apiVersion: batch/v1
kind: Job
metadata:
  name: fib-load
  labels:
    app: fib
    component: load
spec:
  template:
    spec:
      containers:
      - name: fib-load
        image: errm/ab
        args: ["-n30000", "-c4", "fib/30"]
      restartPolicy: OnFailure
