kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: fib
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fib
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 20M
