apiVersion: apps/v1
kind: Deployment
metadata:
  name: randserver
spec:
  selector:
    matchLabels:
      app: randserver
  template:
    metadata:
      labels:
        app: randserver
    spec:
      containers:
      - image: errm/randserver
        name: randserver
        volumeMounts:
        - mountPath: /data
          name: data
        securityContext:
          readOnlyRootFilesystem: true
      volumes:
      - name: data
        emptyDir: {}
